### ISSUE TITLE
Lists

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/bela_newBlog#5]
`<ul><li>` and `<ol><li>` have `list-style-type` set to none (so you see no circles nor numbers).
I think this should be removed.

Also, there is a weird css rule (it is in the compiled `main.css`, got it from the chrome inspector):
```
.post p:first-child {
    font-size: 1.25em;
}
```
which makes the test of list items look larger. I think this should be removed.

**Comment by disastrid** [comment]
I think this is missing some text. What do you think `<ul>` and `<ol>` should be set to? list-style-type: none is conventional, what do you think it should be?

As for that line of css, It's not a weird rule - this is what makes the text of the first paragraph of a post larger and is an intended effect. I don't know what you mean by "makes the test of list items look larger" - can you screenshot an example?

**Comment by giuliomoro** [comment]
Edited the post. I think it `list-style-type` should be removed (or set to `initial` or `inherit` I believe).
Alright, have a look at this 

https://disastrid.github.io/bela_newBlog/2016/04/07/bela-analogue-vs-audio/

scroll down to "Constant sample rate: where the other ADC and DAC could ": THAT paragraph is rendered with `1.25em`.
No idea why, given that it is not the first `<p>`. Also, no idea why that and the following one are the only two `<li>` which contain a `<p>`.

**Comment by disastrid** [comment]
I think what's causing some issues here is that this particular use of `<ul><li></li></ul>` isn't syntactically correct (markup makes us conform to hard and fast rules). In these lists you're rendering an `<li>` and then following it up with a paragraph on a new line, which is not included in the `<li>` element but instead rendered as a separate `<p>` (which is why the spacing between those elements is not ideal). List elements are supposed to be just that, atomic elements - not collections of paragraphs. There's not really any reason, syntactically or otherwise, to use lists here; they're sections led by a line of bold text and don't need any other markup. 

As for the paragraph rendering at 1.25em: If you inspect the source you'll see that you're rendering a `<p>` inside each of those `<li>` elements, and as the first `<p>` child of an element inside the `post` class  it's hooking into the increased size. Setting the font to `initial` or `inherit` doesn't include the line heights or other things that the root `<p>` elements are getting and the text will look different. 

To avoid all this, I would really recommend sticking to markdown rules for the use of HTML elements; there is a wide interpretation of what HTML syntax actually means and I disagree with some of the decisions made in markdown, but if you don't play by those rules CSS will go a bit nuts.

**Comment by giuliomoro** [comment]
Cool.

github allows to leave a white space at the end of a line 
to obtain 
arbitrary line 
breaks (`<br \>`) 
without creating 

a whole new paragraph `<p>`.

Is this achievable here?

**Comment by disastrid** [comment]
The link to the syntax is in the readme. I don't control Kramdown markdown. The reference is here: https://kramdown.gettalong.org/syntax.html

**Comment by giuliomoro** [comment]
RTFM!
lovely
> If you want to have an explicit line break (i.e. a <br /> tag) you need to end a line with two or more spaces or two backslashes!

thanks

**Comment by giuliomoro** [comment]
Reopened as a reminder, because I forgot that the actual issue is

>I think it `list-style-type` should be removed (or set to `initial` or `inherit` I believe).

Also, `<li>` items could use some `padding-bottom`.

**Comment by disastrid** [comment]
List styles merged from Sample library.
